services:
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - "8085:8080"

  db:
    image: mysql:8.4
    container_name: mysql_forohub
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: forohub
      MYSQL_DATABASE: db_forohub
    ports:
      - "3306:3306"
    volumes:
      - "./mysql_forohub:/var/lib/mysql"
